name: Build and Deploy
on: 
  push:
    paths: ["src/**"] # Trigger the action only when files change in the folders defined here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build ğŸ›ï¸
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        run: npm i
        run: npm run build
      - name: Deploy ğŸš€
        run: npm run deploy-storybook -- --ci